apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  selector:
    app: monitoring
  ports:
  - name: blackbox-exporter
    protocol: TCP
    port: 9115
    targetPort: 9115
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100
  - name: cadvisor
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: smart-ocr
    protocol: TCP
    port: 5001
    targetPort: 5001
  - name: my-passive
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
