apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:latest
        ports:
        - containerPort: 9115
        volumeMounts:
        - mountPath: /config
          name: blackbox-config-volume
        command: ["--config.file=/config/blackbox.yml"]

      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config-volume
        command: ["--config.file=/etc/prometheus/prometheus.yml"]

      - name: alertmanager
        image: quay.io/prometheus/alertmanager
        ports:
        - containerPort: 9093
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanager-config-volume
        command: ["--config.file=/etc/alertmanager/alertmanager.yml"]

      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000

      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100

      - name: cadvisor
        image: google/cadvisor:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-rootfs
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-var-run
          readOnly: true
        - mountPath: /sys
          name: cadvisor-sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-docker
          readOnly: true

      - name: smart-ocr
        image: mightysanjay/smart-ocr:v1
        ports:
        - containerPort: 5001
        stdin: true
        tty: true
        command: ["sh", "-c", "./start.sh && tail -f /dev/null"]

      - name: my-passive
        image: mightysanjay/my-passive:v2
        ports:
        - containerPort: 5000
        stdin: true
        tty: true
        command: ["sh", "-c", "./start.sh && tail -f /dev/null"]

      volumes:
      - name: blackbox-config-volume
        hostPath:
          path: D:/Documents/devops/assignment/prometheus-alertmanager-blackbox-container/blackbox_exporter
          type: Directory 
      - name: prometheus-config-volume
        hostPath:
          path: D:/Documents/devops/assignment/prometheus-alertmanager-blackbox-container/prometheus
          type: Directory
      - name: alertmanager-config-volume
        hostPath:
          path: D:/Documents/devops/assignment/prometheus-alertmanager-blackbox-container/alertmanager
          type: Directory
      - name: cadvisor-rootfs
        hostPath:
          path: /
      - name: cadvisor-var-run
        hostPath:
          path: /var/run
      - name: cadvisor-sys
        hostPath:
          path: /sys
      - name: cadvisor-docker
        hostPath:
          path: /mnt/c/ProgramData/docker
          type: Directory
