apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
spec:
  selector:
    app: blackbox-exporter
  ports:
  - port: 9115
    targetPort: 9115
    nodePort: 30003
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter-container
        image: quay.io/prometheus/blackbox-exporter:latest
        ports:
        - containerPort: 9115
        args:
        - "--config.file=/config/blackbox.yaml"
        volumeMounts:
        - name: blackbox-exporter-config-volume
          mountPath: /config
      volumes:
      - name: blackbox-exporter-config-volume
        configMap:
          name: blackbox-exporter-config
