apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      name: grafana
      labels:
        name: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana/grafana
        ports:
        - containerPort: 3000
