apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus-container
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-volume
        command: ["--config.file=/etc/prometheus/prometheus.yml"]

      volumes:
      - name: prometheus-volume
        hostPath:
          path: ./prometheus
          type: Directory
